# Generated by Django 6.0.3 on 2026-03-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_text',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_pdf',
            field=models.FileField(blank=True, help_text="User's master CV PDF file", null=True, upload_to='cvs/'),
        ),
    ]
