# Generated by Django 6.0.3 on 2026-03-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_cv_text_userprofile_cv_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
