# Generated by Django 6.0.3 on 2026-04-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_access_token',
            field=models.TextField(blank=True, help_text='Google Calendar access token (should be encrypted in production)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_refresh_token',
            field=models.TextField(blank=True, help_text='Google Calendar refresh token (should be encrypted in production)', null=True),
        ),
    ]
