# Generated by Django 6.0.3 on 2026-04-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='google_refresh_token',
        ),
    ]
