# Generated by Django 6.0.3 on 2026-04-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_google_oauth_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
