# Generated by Django 6.0.3 on 2026-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Stored full job description scraped or manually entered.'),
        ),
    ]
