# Generated by Django 6.0.3 on 2026-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
